### ISSUE TITLE
Uncaught TypeError: Cannot read property 'created' of undefined 

### ISSUE THREAD

**Issue by ghost** [gamelab/Platform-Blueprint#1]
Switched from canvas renderer, to webgl renderer, and game does not appear.

Console log error:
Uncaught TypeError: Cannot read property 'created' of undefined. Line  kiwi.js:14203

Code where the error occurs:
GLTextureManager.prototype.useTexture = function (gl, glTextureWrapper) {
    if (!glTextureWrapper.created || !glTextureWrapper.uploaded) {

**Comment by rosskettle** [comment]
Preloader special case code was causing the problem. Ben to provide Phil with new preloader code.
